MODEL:
  folder: "/opt/cgan/Jurre_Brishti/model-config/model-weights"
  checkpoint: 316800

INPUT:
  folder: "/opt/cgan/forecasts/cgan-ifs-6h-ens"
  file: "IFS_20250115_00Z.nc"
  start_hour: 30
  end_hour: 54

OUTPUT:
  folder: "/opt/cgan/jobs/jurre-brishti-count"
  ensemble_members: 1000
