name: Build and Publish API Service to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - nginx/**
      - .github/workflows/build-api.yaml
      - api.Dockerfile
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker image meta attributes
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fast-cgan-api
          tags: |
            ${{ secrets.GITHUB_SHA }}
            latest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Build and push web proxy image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: api.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/fast-cgan-api
          short-description: cGAN forecasts visualization API Service
          enable-url-completion: true
      
      - name: Logout of docker registry
        run: docker logout
