name: Build and Publish to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker image meta attributes
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_USER }}/sewaa-proxy-server
          tags: |
            ${{ secrets.GITHUB_SHA }}
            latest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Check REGISTRY_USER
        run: echo ${{ secrets.REGISTRY_USER }}

      - name: Check REGISTRY_IMAGE
        run: echo ${{ env.REGISTRY_IMAGE }}

      - name: Available QEMU platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Available buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Check git commit SHA
        run: echo ${{ secrets.GITHUB_SHA }}

      - name: Build and push web proxy image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: web.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/arm,linux/386
      
      - name: Logout of docker registry
        run: docker logout
